Sprint1v2 Lehen sprint amaituta
oier-elorrieta/E4T7 pull request #1
Opened 2024-04-23 08:26 UTC by Jonnaan

2024-04-23 10:19 UTC, oier-elorrieta requested changes

2024-04-23 10:19 UTC, oier-elorrieta commented on src/model/metodoak/Metodoak.java
> +package model.metodoak;
Metodoak ez al da izen generikoegia? Zer motatatko metodoak sartuko dira hemen? Kajon desastre bat?

2024-04-23 10:19 UTC, oier-elorrieta commented on src/model/sql/SQLKonexioa.java
> +package model.sql;
Klase hau konexioa deitzen da, baina konexioa baino askoz gauza gehiago egiten dira, ez? DAO klaserik ez?

2024-04-23 10:19 UTC, oier-elorrieta commented on src/view/Menua.java
> +package view;
View klaseetan iruzkinen bat gehiago agian faltan botatzen dut.

2024-04-23 10:38 UTC, Markel05-Elorrieta commented on src/model/metodoak/Metodoak.java
> +package model.metodoak;
"View_metodoak" izenera aldatuta eta bertan sartu ditut botoien metodoak eta konprobaketa

2024-04-23 10:40 UTC, Markel05-Elorrieta commented on src/model/sql/SQLKonexioa.java
> +package model.sql;
Izena aldatuta "SQLInterakzioa" -ra. Ez dugu DAO klaserik egin, bertan dago interakzioak klase guztiekin.

2024-04-23 10:49 UTC, Markel05-Elorrieta commented on src/view/Menua.java
> +package view;
Iruzkinak gehituta.

2024-04-24 07:24 UTC, oier-elorrieta requested changes
Aladatu main-en detailea eta deprecated-arena eta nigatik, aurrera

2024-04-24 07:24 UTC, oier-elorrieta commented on src/view/Erregistroa.java
> +						if (passwordField.getText().equals(passwordFieldConfirm.getText())) {
JPasswordField baterako gettext deprecated dago. Ba al dago aldatzerik beste metodo batengatik?

2024-04-24 07:24 UTC, oier-elorrieta commented on src/view/Login.java
> +	public static void main(String[] args) {
Eso que hace ahí?

2024-04-24 07:27 UTC, Markel05-Elorrieta commented on src/view/Erregistroa.java
> +						if (passwordField.getText().equals(passwordFieldConfirm.getText())) {
Zuzenduta

2024-04-24 07:27 UTC, Markel05-Elorrieta commented on src/view/Login.java
> +	public static void main(String[] args) {
Borrao

2024-04-24 07:35 UTC, oier-elorrieta approved these changes

2024-04-24 11:04 UTC, OierZub approved these changes
POJOei buelta bat eman beharko diozue 2. Sprint-ari begira.

2024-04-24 11:11 UTC, merged